---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

**UNDER CONSTRUCTION**

# hidrowebdown

Downloading data from the major database of hydrological data in Brazil ([Hidroweb](http://hidroweb.ana.gov.br) - National Water Agency ([ANA](www.ana.gov.br)) from R.

## Installation

You can install hidrowebdown from GitHub with:

```{r gh-installation, eval = FALSE}
# install.packages("devtools")
devtools::install_github("lhmet/hidrowebdown")
```

## Example

You can choose a hydrological station looking at the data `hidro_metadata`.

```{r}
library(hidrowebdown)
# metadata
head(hidro_metadata)
comment(hidro_metadata)
```

To download data, for some stations:

```{r}
stns <- c("42650000", "00252001")
opts <- c("Vazao", "Chuva")
down_stns <- hidroweb_down(stations = stns, 
                     options = opts, 
                     verbose = TRUE, 
                     dest.dir = "../", 
                     meta = TRUE)
down_stns
```

